config/routes.rb
Rails.application.routes.draw do
  resources :criteria
  resources :experts
  resources :ratings
  resources :eval_methods
  resources :questions
  resources :commissions
  resources :teachers
  resources :marks

  resources :defense_processes do
    resources :groups
  end

  resources :students
  
  root 'welcome#index'
  devise_for :users, path: 'users'

  get 'board/index'

  get 'locale/:lang', action: :switch_locale, controller: 'application', as: 'locale'

  resources :protocols, only: [:show]

  get 'create_pdf_protocol', action: :create_pdf, controller: 'students'

  get 'new_experts_list', action: :add_experts_list, controller: 'experts'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def init_secretary
    cannot :create, Mark
    can :crud, [DefenseProcess, Group, Student, Diploma, Protocol, Commission]
  end

  def init_commissioner
    can [:create, :edit], Mark
  end

  def initialize(user)
  
      user ||= User.new
      
      alias_action :create, :read, :update, :destroy, to: :crud
      
      if !user.new_record?
        # can :crud, [DefenseProcess, Student, Diploma]
        # can :create_pdf, [Student]
        can :read, :all

        case user.role
          when "secretary"
            init_secretary
          when "commissioner"
            init_commissioner
        end
      
      else
        cannot :crud, [DefenseProcess, Group, Student, Diploma]
      end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/commission.rb
class Commission < ApplicationRecord
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :teachers, class_name: 'Teacher', through: :commision_assignments
    has_many :groups, class_name: 'Group'

    validates :number, presence: true

    def eval_method
        return eval_method_id.nil? ? "Метод оцінки не визначений" : EvalMethod.find(eval_method_id).name
    end

    def head
        return Teacher.find(head_id)
    end

end

app/models/criterium.rb
class Criterium < ApplicationRecord
  belongs_to :eval_method
  belongs_to :expert
end

app/models/diploma.rb
class Diploma < ApplicationRecord
  belongs_to :student
  has_many :questions, :dependent => :destroy
  has_many :marks, :dependent => :destroy
end

app/models/eval_method.rb
class EvalMethod < ApplicationRecord
end

app/models/expert.rb
class Expert < ApplicationRecord
  belongs_to :eval_method
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :defense_process
  has_many :students, :dependent => :destroy

  def commission_info
    commission = Commission.find(commission_id)
    if !commission.nil?
      "Назва комісії: #{ commission.name }, номер комісії: #{ commission.number }"
    else
      "Немає комісії"
    end
  end

  def commission
    return Commission.find(commission_id)
  end

  def commission_head
    commission = Commission.find(commission_id)
    teacher = Teacher.find(commission.head_id)
    return teacher
  end
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :diploma
  validates :mark, :inclusion => { in: 0..12 }
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  belongs_to :student

  def teacher
    Teacher.find_by(id: teacher_id)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :diploma
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :eval_method
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  belongs_to :teacher
  has_one :protocol, dependent: :destroy
  has_one :diploma, class_name: "Diploma", dependent: :destroy

  accepts_nested_attributes_for :diploma

  def get_teacher_lfp
    teacher = Teacher.find_by(id: self.teacher_id)
    return "#{ teacher.last_name } #{ teacher.first_name } #{ teacher.patronymic}"
  end

  # def lfp
  #   return "#{ student.last_name } #{ student.first_name } #{ student.patronymic}"
  # end

  def get_group
    group = Group.find_by(id: self.group_id)
    return group
  end

  def commission_teachers
    commission_teacher_ids = Commission.find(group_id).teacher_ids
    teachers_array = Array.new
    
    commission_teacher_ids.each do |teacher_id|
      teachers_array.push(Teacher.find(teacher_id))
    end

    return teachers_array
  end

  def leader_teacher
    Teacher.find_by(id: teacher_id)
  end

  def leader_teacher_info
    teacher = leader_teacher
    return "#{ teacher.academic_status }, #{ teacher.position }, #{ teacher.lfp }"
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :students
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :commissions, class_name: 'Commission', through: :commision_assignments

    def lfp
        return "#{last_name} #{first_name} #{patronymic}"
    end

    def l_initials
        return "#{last_name} #{first_name[0]}.#{patronymic[0]}."
    end

    def fname_lname_upper
        return "#{first_name} #{last_name.upcase}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:commissioner, :secretary]
  after_initialize :set_default_role, :if => :new_record?

  has_many :defense_processes

  def set_default_role
    self.role ||= :commissioner
  end

end

app/controllers/defense_processes_controller.rb
class DefenseProcessesController < ApplicationController
  load_and_authorize_resource :through => :current_user
  before_action :set_defense_process, only: %i[ show edit update destroy ]

  def index
    @defense_processes = DefenseProcess.all
  end

  def show
    @group = Group.new
  end

  def new
    @defense_process = DefenseProcess.new
  end

  def edit
  end

  def create
    @defense_process = DefenseProcess.new(defense_process_params)
    @defense_process.user_id = current_user.id

    if @defense_process.save
      flash[:notice] = "Новий захист успішно створений!"
    else
      flash[:alert] = "Щось пішло не так :( Новий захист не створений!" 
    end

    redirect_back fallback_location: root_path
  end

  def update
      if @defense_process.update(defense_process_params)
        flash[:notice] = "Дані захисту успішно оновлений!"
      else
        flash[:alert] = "Щось пішло не так :( Захист не оновився!" 
      end

    redirect_to defense_process_url(@defense_process)
  end

  def destroy
    @defense_process.destroy

    respond_to do |format|
      format.html { redirect_to defense_processes_url, notice: "Захист успішно видалений." }
      format.json { head :no_content }
    end
  end

  private
    def set_defense_process
      @defense_process = DefenseProcess.find(params[:id])
    end

    def defense_process_params
      params.fetch(:defense_process, {}).permit(:nameID)
    end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/defense_processes_helper.rb
module DefenseProcessesHelper
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/defense_processes/_defense_process.html.erb
<div id="<%= dom_id defense_process %>">
    <b>Назва захисту</b> : <%= defense_process.nameID %>
</div>

app/views/defense_processes/_form.html.erb
<%= form_with(model: defense_process) do |form| %>
  <% if defense_process.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(defense_process.errors.count, "error") %> prohibited this defense_process from being saved:</h2>

      <ul>
        <% defense_process.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="field">
      <%= form.label "Назва" %><br />
      <%= form.text_field :nameID, class: "form-control" %>
    </div>

    <%= form.submit "Зберігти", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/defense_processes/edit.html.erb
<%= render partial: "/shared/icon_links_btns", locals: { back: defense_processes_path, edit: false, delete: false, eye: @defense_process } %>

<h1>Editing defense process</h1>

<%= render "form", defense_process: @defense_process %>

app/views/defense_processes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t("defense_process.defense_processes")%></h1>

<div id="defense_processes">
  <% @defense_processes.each do |defense_process| %>
    <div class="defense_process_wrap">
      <%= render defense_process %>
      <%= link_to defense_process  do %>
        <i class="bi bi-eye"></i>
      <% end %>
    </div>
  <% end %>
</div>

<% if can? :create, DefenseProcess %>
  <%= link_to t("defense_process.new"), new_defense_process_path, class: "btn btn-outline-primary" %>
<% end %>

app/views/defense_processes/new.html.erb
<div>
  <%= link_to defense_processes_path do %>
    <i class="bi bi-arrow-left-circle defense"></i>
  <% end %>
</div>

<h1>Новий захист</h1>

<%= render "form", defense_process: @defense_process %>

app/views/defense_processes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: "/shared/icon_links_btns", locals: {back: defense_processes_path, edit: { path: edit_defense_process_path, resource: @defense_process }, delete: { path: defense_process_path, resource: @defense_process }, eye: false} %>

<%= render @defense_process %>

<div class="defense_container">
  <% if can? :create, @group %>
     <button class="btn btn-outline-success btn-create-defense"><%= t("group.create")%></button>
  <% end %>

  <div class="form_container">
    <h1><%= t("group.new") %></h1>

    <%= form_for @group, url: defense_process_groups_path(@defense_process.id), method: :post do |form| %>
      <div>

      <div class="field">
        <%= form.label "Форма навчання" %><br />
        <%= form.select(:form, [["Денна", "Денна"], ["Заочна", "Заочна"]], {selected: "Денна"}, { class: "form-select" }) %>
      </div>

      <div class="field">
        <%= form.label "Спеціалізація" %><br />
        <%= form.text_field :specialization, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label "Назва групи" %><br />
        <%= form.text_field :name_number, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label "Шифр спеціальності" %><br />
        <%= form.text_field :specialty_code, data: { numeric: true }, class: "form-control" %>
      </div>
      
      <div class="field">
        <%= form.label "Спеціальність" %><br />
        <%= form.text_field :specialty_title, class: "form-control" %>
      </div>

      <div class="field dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Вибрати комісію
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <%= form.collection_check_boxes(:commission_id, Commission.all, :id, :name) do |b| %>
            <li>
              <div class="dropdown-item">
                <%= b.label(:"data-value" => b.value) { b.check_box + ' ' + b.text } %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

        <%= form.submit t("group.create"), class: "btn btn-success" %>
      </div>
    <% end %>

  </div>
</div>

<h1><%= t("group.groups") %></h1>

<div id="groups">
  <% @defense_process.groups.each do |group| %>
    <p>
      <b>Назва групи</b> : <%= group.name_number %> <%= group.specialization%>
      <%= link_to defense_process_group_path(@defense_process.id, group.id), method: :get  do %>
        <i class="bi bi-eye defense"></i>
      <% end %>
    </p>
  <% end %>
</div>