config/routes.rb
Rails.application.routes.draw do
  resources :criteria
  resources :experts
  resources :ratings
  resources :eval_methods
  resources :questions
  resources :commissions
  resources :teachers
  resources :marks

  resources :defense_processes do
    resources :groups
  end

  resources :students
  
  root 'welcome#index'
  devise_for :users, path: 'users'

  get 'board/index'

  get 'locale/:lang', action: :switch_locale, controller: 'application', as: 'locale'

  resources :protocols, only: [:show]

  get 'create_pdf_protocol', action: :create_pdf, controller: 'students'

  get 'new_experts_list', action: :add_experts_list, controller: 'experts'

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  belongs_to :teacher
  has_one :protocol, dependent: :destroy
  has_one :diploma, class_name: "Diploma", dependent: :destroy

  accepts_nested_attributes_for :diploma

  def get_teacher_lfp
    teacher = Teacher.find_by(id: self.teacher_id)
    return "#{ teacher.last_name } #{ teacher.first_name } #{ teacher.patronymic}"
  end

  # def lfp
  #   return "#{ student.last_name } #{ student.first_name } #{ student.patronymic}"
  # end

  def get_group
    group = Group.find_by(id: self.group_id)
    return group
  end

  def commission_teachers
    commission_teacher_ids = Commission.find(group_id).teacher_ids
    teachers_array = Array.new
    
    commission_teacher_ids.each do |teacher_id|
      teachers_array.push(Teacher.find(teacher_id))
    end

    return teachers_array
  end

  def leader_teacher
    Teacher.find_by(id: teacher_id)
  end

  def leader_teacher_info
    teacher = leader_teacher
    return "#{ teacher.academic_status }, #{ teacher.position }, #{ teacher.lfp }"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource :student
  load_and_authorize_resource :group, permit: :create
  before_action :set_student, only: %i[ show edit update destroy ]

  def index
    @students = Student.all
  end

  def show
    # create_pdf
    
    @diploma = @student.diploma
    @question = Question.new
    @mark = Mark.new

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", template: "students/show", formats: [:html], :encoding => 'UTF-8'
      end
    end
  end

  def new
    @student = Student.new
    @diploma = @student.build_diploma(params[:diploma])
  end

  def edit
    @teachers = Teacher.all
  end

  def create
    @student = Student.new(student_params)
    @student.group_id = params[:group_id]

    respond_to do |format|
      if @student.save
        @diploma = @student.create_diploma(params[:diploma])

        format.html { redirect_back fallback_location: root_path, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @student.diploma = Diploma.new(params[:diploma])
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    defense_process_id = @student.get_group.defense_process_id
    group_id = @student.group_id

    @student.destroy

    respond_to do |format|
      format.html { redirect_to defense_process_group_path(defense_process_id, group_id), notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Start
  def create_pdf
    pdf_html = ActionController::Base.new.render_to_string(template: 'protocols/show', layout: false)
    pdf = WickedPdf.new.pdf_from_string(pdf_html,
      :encoding => 'UTF-8',
      :page_size => 'A4',
      :orientation => 'Portrait')
    # pdf = WickedPdf.new.pdf_from_string('<!doctype html><html><head></head><body>Привіт</body></html>',
    #   :encoding => 'UTF-8',
    #   :page_size => 'A4',
    #   :orientation => 'Portrait')

      send_data(pdf, :filename  => 'myPDF', :disposition => 'attachment')
      
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.fetch(:student, [:diploma]).permit(:full_name, :theme, :date, :gender, :teacher_id, :commission_id, diploma_attributes: [:theme, :pages, :presentation, :language, :student_id, :mark, :sample_type])
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="student_container">
    <div class="field">
      <%= form.label "ПІБ" %><br />
      <%= form.text_field :full_name, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Стать" %><br />
      <%= form.select(:gender, [["Жінка", "feminine"], ["Чоловік", "masculine"]], {selected: student.gender}, { class: "form-select" }) %>
    </div>

    <div class="field">
      <%= form.label "Тема диплому" %><br />
      <%= form.text_field :theme, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Керівник" %><br />
      <div class="from-list">
        <%= form.select(:teacher_id, [""] + @teachers.map { |teacher| [ teacher.lfp, teacher.id ] }, { selected: student.teacher_id }, { class: "form-select teacher_enter-from-list" }) %>
      </div>
    </div>

    <div class="field">
      <%= form.label "Дата захисту" %><br />
      <%= form.date_field :date, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: "form-control" %>
    </div>

    <div class="diploma__container">
        <h4>Інформація про диплом</h4>

        <%= form.fields_for :diploma_attributes do |diploma_f| %>

          <div>
            <%= diploma_f.label :theme, style: "display: block" %>
            <%= diploma_f.text_field :theme, value: student.diploma.theme, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :pages, style: "display: block" %>
            <%= diploma_f.number_field :pages, value: student.diploma.pages, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :presentation, style: "display: block" %>
            <%= diploma_f.number_field :presentation, value: student.diploma.presentation, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :language, style: "display: block" %>
            <%= diploma_f.text_field :language, value: "українською", class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :mark, style: "display: block" %>
            <%= diploma_f.number_field :mark, value: student.diploma.mark, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :sample_type, style: "display: block" %>
            <%= diploma_f.text_field :sample_type, value: student.diploma.sample_type, class: "form-control" %>
          </div>
        
        <% end %>

      </div>

      <%= form.submit "Додати студента", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
    <p>
        <b>ПІБ</b> : <%= student.full_name %> <br />
        <b>Стать</b> : <%= student.gender == "feminine" ? "Жінка" : "Чоловік"  %> <br />
        <b>Тема диплому</b> : <%= student.theme %> <br />
        <b>Керівник</b> : 
        <%= student.get_teacher_lfp %> <br />
        <b>Дата захисту</b> : <%= student.date %> <br />
        <div class="diploma__container">
            <h4>Інформація про диплом</h4>

          <div>
            <%= render student.diploma %>
          </div>
        </div>

        <% if can? :create, Protocol %>
          <%= link_to student_path(student.id), method: :get  do %>
              <i class="bi bi-eye defense"></i>
          <% end %>
          <%= link_to 'Сформувати протокол', protocol_path(student_id: student.id) %>
          <%= link_to 'pdf', protocol_path(format: :pdf) %>
          <%= link_to 'Сформувати протокол в PDF', create_pdf_protocol_path %>
        <% end %>
    </p>
</div>

app/views/students/edit.html.erb
<%= render partial: "/shared/icon_links_btns", locals: { back: @student, edit: false, delete: false, eye: @student } %>

<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: "/shared/icon_links_btns", locals: { back: :back, edit: { path: edit_student_path(@student), resource: @student }, delete: { path: student_path, resource: @student }, eye: false } %>

<%= render @student %>

<div>
  <%= link_to "Open list of students", students_path %>
</div>