config/routes.rb
Rails.application.routes.draw do
  resources :criteria
  resources :experts
  resources :ratings
  resources :eval_methods
  resources :questions
  resources :commissions
  resources :teachers
  resources :marks

  resources :defense_processes do
    resources :groups
  end

  resources :students
  
  root 'welcome#index'
  devise_for :users, path: 'users'

  get 'board/index'

  get 'locale/:lang', action: :switch_locale, controller: 'application', as: 'locale'

  resources :protocols, only: [:show]

  get 'create_pdf_protocol', action: :create_pdf, controller: 'students'

  get 'new_experts_list', action: :add_experts_list, controller: 'experts'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def init_secretary
    cannot :create, Mark
    can :crud, [DefenseProcess, Group, Student, Diploma, Protocol, Commission]
  end

  def init_commissioner
    can [:create, :edit], Mark
  end

  def initialize(user)
  
      user ||= User.new
      
      alias_action :create, :read, :update, :destroy, to: :crud
      
      if !user.new_record?
        # can :crud, [DefenseProcess, Student, Diploma]
        # can :create_pdf, [Student]
        can :read, :all

        case user.role
          when "secretary"
            init_secretary
          when "commissioner"
            init_commissioner
        end
      
      else
        cannot :crud, [DefenseProcess, Group, Student, Diploma]
      end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/commission.rb
class Commission < ApplicationRecord
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :teachers, class_name: 'Teacher', through: :commision_assignments
    has_many :groups, class_name: 'Group'

    validates :number, presence: true

    def eval_method
        return eval_method_id.nil? ? "Метод оцінки не визначений" : EvalMethod.find(eval_method_id).name
    end

    def head
        return Teacher.find(head_id)
    end

end

app/models/criterium.rb
class Criterium < ApplicationRecord
  belongs_to :eval_method
  belongs_to :expert
end

app/models/defense_process.rb
class DefenseProcess < ApplicationRecord
    belongs_to :user
    has_many :groups, :dependent => :destroy

end

app/models/diploma.rb
class Diploma < ApplicationRecord
  belongs_to :student
  has_many :questions, :dependent => :destroy
  has_many :marks, :dependent => :destroy
end

app/models/eval_method.rb
class EvalMethod < ApplicationRecord
end

app/models/expert.rb
class Expert < ApplicationRecord
  belongs_to :eval_method
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :defense_process
  has_many :students, :dependent => :destroy

  def commission_info
    commission = Commission.find(commission_id)
    if !commission.nil?
      "Назва комісії: #{ commission.name }, номер комісії: #{ commission.number }"
    else
      "Немає комісії"
    end
  end

  def commission
    return Commission.find(commission_id)
  end

  def commission_head
    commission = Commission.find(commission_id)
    teacher = Teacher.find(commission.head_id)
    return teacher
  end
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :diploma
  validates :mark, :inclusion => { in: 0..12 }
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  belongs_to :student

  def teacher
    Teacher.find_by(id: teacher_id)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :diploma
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :eval_method
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  belongs_to :teacher
  has_one :protocol, dependent: :destroy
  has_one :diploma, class_name: "Diploma", dependent: :destroy

  accepts_nested_attributes_for :diploma

  def get_teacher_lfp
    teacher = Teacher.find_by(id: self.teacher_id)
    return "#{ teacher.last_name } #{ teacher.first_name } #{ teacher.patronymic}"
  end

  # def lfp
  #   return "#{ student.last_name } #{ student.first_name } #{ student.patronymic}"
  # end

  def get_group
    group = Group.find_by(id: self.group_id)
    return group
  end

  def commission_teachers
    commission_teacher_ids = Commission.find(group_id).teacher_ids
    teachers_array = Array.new
    
    commission_teacher_ids.each do |teacher_id|
      teachers_array.push(Teacher.find(teacher_id))
    end

    return teachers_array
  end

  def leader_teacher
    Teacher.find_by(id: teacher_id)
  end

  def leader_teacher_info
    teacher = leader_teacher
    return "#{ teacher.academic_status }, #{ teacher.position }, #{ teacher.lfp }"
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :students
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :commissions, class_name: 'Commission', through: :commision_assignments

    def lfp
        return "#{last_name} #{first_name} #{patronymic}"
    end

    def l_initials
        return "#{last_name} #{first_name[0]}.#{patronymic[0]}."
    end

    def fname_lname_upper
        return "#{first_name} #{last_name.upcase}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:commissioner, :secretary]
  after_initialize :set_default_role, :if => :new_record?

  has_many :defense_processes

  def set_default_role
    self.role ||= :commissioner
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource :defense_process
  load_and_authorize_resource :group, :through => :defense_process
  before_action :set_group, only: %i[ show edit update destroy ]

  def show
    @student = Student.new
    @teachers = Teacher.all
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = @defense_process.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to defense_process_group_url(@defense_process.id, @group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to defense_process_group_url(@defense_process.id, @group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to defense_process_url(@defense_process.id), notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_group
      @group = @defense_process.groups.find(params[:id])
    end

    def group_params
      params.fetch(:group, {}).permit(:form, :specialization, :name_number, :specialty_code, :degree, :commission_id)
    end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: [defense_process, group]) do |form| %>

<% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>

    <div class="field">
      <%= form.label "Форма навчання" %><br />
      <%= form.select(:form, [["Денна", "Денна"], ["Заочна", "Заочна"]], { selected: "Денна" }, { class: "form-select" }) %>
    </div>

    <div class="field">
      <%= form.label "Спеціалізація" %><br />
      <%= form.text_field :specialization, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Назва групи" %><br />
      <%= form.text_field :name_number, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Шифр спеціальності" %><br />
      <%= form.text_field :specialty_code, data: { numeric: true }, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Ступінь вищої освіти" %><br />
      <%= form.text_field :degree, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label "Вибрати комісію" %><br />
      <%= form.select(:commission_id, [""] + Commission.all.map { |commission| [ "#{commission.name} #{commission.number}", commission.id ] }, {selected: ""}, { class: "form-select" }) %>
    </div>

    <%= form.submit "Редагувати", class: "btn btn-success" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
    <p><b>Форма навчання</b> : <%= group.form %></p>
    <p><b>Спеціалізація</b> : <%= group.specialization %></p>
    <p><b>Назва групи</b> : <%= group.name_number %></p>
    <p><b>Шифр спеціальності</b> : <%= group.specialty_code %></p>
    <p><b>Комісія</b>: <%= group.commission_info %></p>
</div>

app/views/groups/edit.html.erb
<%= render partial: "/shared/icon_links_btns", locals: { back: defense_process_path(@defense_process.id), edit: false, delete: false, eye: defense_process_group_path(@defense_process.id) } %>

<h1>Editing group</h1>

<%= render "form", group: @group, defense_process: @defense_process %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group, defense_process: @defense_process %>

<br>

<div>
  <%= link_to "Back to groups", defense_process_groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: "/shared/icon_links_btns", locals: { back: defense_process_path(@defense_process.id), edit: { path: edit_defense_process_group_path, resource: @group }, delete: { path: defense_process_group_path, resource: @group }, eye: false } %>

<%= render @group %>

<% if can? :create, @student %>
  <div class="student_container">
    <button class="btn btn-outline-success btn-create-student">Додати студента в группу</button>

  <div class="form_container">
    <h1><%= t("student.new") %></h1>

    <%= form_for @student, url: students_path(group_id: @group), method: :post do |form| %>
      <div>

      <div class="field">
        <%= form.label "ПІБ" %><br />
        <%= form.text_field :full_name, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label "Стать" %><br />
        <%= form.select(:gender, [["Жінка", "feminine"], ["Чоловік", "masculine"]], {selected: @student.gender}, { class: "form-select" }) %>
      </div>

      <div class="field">
        <%= form.label "Тема диплому" %><br />
        <%= form.text_field :theme, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label "Керівник" %><br />
        <div class="from-list">
          <%= form.select(:teacher_id, [""] + @teachers.map { |teacher| [ teacher.lfp, teacher.id ] }, {selected: ""}, { class: "form-select teacher_enter-from-list" }) %>
        </div>
      </div>

      <div class="field">
        <%= form.label "Дата захисту" %><br />
        <%= form.date_field :date, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: "form-control" %>
      </div>

      <div class="diploma__container">
        <h2>Інформація про диплом</h2>

        <%= form.fields_for :diploma do |diploma_f| %>

          <div>
            <%= diploma_f.label :theme, style: "display: block" %>
            <%= diploma_f.text_field :theme, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :pages, style: "display: block" %>
            <%= diploma_f.number_field :pages, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :presentation, style: "display: block" %>
            <%= diploma_f.number_field :presentation, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :language, style: "display: block" %>
            <%= diploma_f.text_field :language, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :mark, style: "display: block" %>
            <%= diploma_f.number_field :mark, class: "form-control" %>
          </div>

          <div>
            <%= diploma_f.label :sample_type, style: "display: block" %>
            <%= diploma_f.text_field :sample_type, class: "form-control" %>
          </div>
        <% end %>

      </div>
        <%= form.submit "Додати студента", class: "btn btn-success" %>
      </div>
    <% end %>

    </div>
  </div>
<% end %>

<div class="student__list">

  <% if(@group.students.size != 0) %>
  
    <h1>Список студентів</h1>

    <table>
      <tr>
        <th></th>
        <th>ПІБ</th>
        <th>Тема диплому</th>
        <th>Керівник</th>
        <th>Дата захисту</th>
        <th></th>
      </tr>
      <% @group.students.each do |student| %>
        <tr>
          <td><%= @group.students.index(student) + 1 %></td>
          <td><%= student.full_name %></td>
          <td><%= student.theme %></td>
          <td>
            <%= student.get_teacher_lfp %> <br />
          </td>
          <td><%= student.date %></td>
          <td>
            <%= link_to student_path(student.id), method: :get  do %>
              <i class="bi bi-eye defense"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      
    </table>

  <% end %>

</div>