config/routes.rb
Rails.application.routes.draw do
  resources :criteria
  resources :experts
  resources :ratings
  resources :eval_methods
  resources :questions
  resources :commissions
  resources :teachers
  resources :marks

  resources :defense_processes do
    resources :groups
  end

  resources :students
  
  root 'welcome#index'
  devise_for :users, path: 'users'

  get 'board/index'

  get 'locale/:lang', action: :switch_locale, controller: 'application', as: 'locale'

  resources :protocols, only: [:show]

  get 'create_pdf_protocol', action: :create_pdf, controller: 'students'

  get 'new_experts_list', action: :add_experts_list, controller: 'experts'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def init_secretary
    cannot :create, Mark
    can :crud, [DefenseProcess, Group, Student, Diploma, Protocol, Commission]
  end

  def init_commissioner
    can [:create, :edit], Mark
  end

  def initialize(user)
  
      user ||= User.new
      
      alias_action :create, :read, :update, :destroy, to: :crud
      
      if !user.new_record?
        # can :crud, [DefenseProcess, Student, Diploma]
        # can :create_pdf, [Student]
        can :read, :all

        case user.role
          when "secretary"
            init_secretary
          when "commissioner"
            init_commissioner
        end
      
      else
        cannot :crud, [DefenseProcess, Group, Student, Diploma]
      end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/commission.rb
class Commission < ApplicationRecord
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :teachers, class_name: 'Teacher', through: :commision_assignments
    has_many :groups, class_name: 'Group'

    validates :number, presence: true

    def eval_method
        return eval_method_id.nil? ? "Метод оцінки не визначений" : EvalMethod.find(eval_method_id).name
    end

    def head
        return Teacher.find(head_id)
    end

end

app/models/criterium.rb
class Criterium < ApplicationRecord
  belongs_to :eval_method
  belongs_to :expert
end

app/models/diploma.rb
class Diploma < ApplicationRecord
  belongs_to :student
  has_many :questions, :dependent => :destroy
  has_many :marks, :dependent => :destroy
end

app/models/eval_method.rb
class EvalMethod < ApplicationRecord
end

app/models/expert.rb
class Expert < ApplicationRecord
  belongs_to :eval_method
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :defense_process
  has_many :students, :dependent => :destroy

  def commission_info
    commission = Commission.find(commission_id)
    if !commission.nil?
      "Назва комісії: #{ commission.name }, номер комісії: #{ commission.number }"
    else
      "Немає комісії"
    end
  end

  def commission
    return Commission.find(commission_id)
  end

  def commission_head
    commission = Commission.find(commission_id)
    teacher = Teacher.find(commission.head_id)
    return teacher
  end
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :diploma
  validates :mark, :inclusion => { in: 0..12 }
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  belongs_to :student

  def teacher
    Teacher.find_by(id: teacher_id)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :diploma
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :eval_method
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  belongs_to :teacher
  has_one :protocol, dependent: :destroy
  has_one :diploma, class_name: "Diploma", dependent: :destroy

  accepts_nested_attributes_for :diploma

  def get_teacher_lfp
    teacher = Teacher.find_by(id: self.teacher_id)
    return "#{ teacher.last_name } #{ teacher.first_name } #{ teacher.patronymic}"
  end

  # def lfp
  #   return "#{ student.last_name } #{ student.first_name } #{ student.patronymic}"
  # end

  def get_group
    group = Group.find_by(id: self.group_id)
    return group
  end

  def commission_teachers
    commission_teacher_ids = Commission.find(group_id).teacher_ids
    teachers_array = Array.new
    
    commission_teacher_ids.each do |teacher_id|
      teachers_array.push(Teacher.find(teacher_id))
    end

    return teachers_array
  end

  def leader_teacher
    Teacher.find_by(id: teacher_id)
  end

  def leader_teacher_info
    teacher = leader_teacher
    return "#{ teacher.academic_status }, #{ teacher.position }, #{ teacher.lfp }"
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :students
    has_many :commision_assignments, class_name: 'CommissionAssignment', dependent: :destroy
    has_many :commissions, class_name: 'Commission', through: :commision_assignments

    def lfp
        return "#{last_name} #{first_name} #{patronymic}"
    end

    def l_initials
        return "#{last_name} #{first_name[0]}.#{patronymic[0]}."
    end

    def fname_lname_upper
        return "#{first_name} #{last_name.upcase}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:commissioner, :secretary]
  after_initialize :set_default_role, :if => :new_record?

  has_many :defense_processes

  def set_default_role
    self.role ||= :commissioner
  end

end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_back_edit_trash_btns.html.erb
<div class="btn-container">
    <% if back %> 
        <%= link_to back do %>
            <i class="bi bi-arrow-left-circle defense"></i>
        <% end %>
    <% end %>

    <% if edit %> 
        <%= link_to edit do %>
             | <i class="bi bi-pencil defense"></i>
        <% end%>
    <% end %>

    <% if delete %> 
        <%= button_to delete, method: :delete, class: "btn-defense_trash" do %>
             | <i class="bi bi-trash defense"></i>
        <% end %>
    <% end %>
</div>

app/views/shared/_header_menu.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <span>Hello <%= current_user.role %>!</span>

    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if can? :create, DefenseProcess %>
                    <li class="nav-item"><%= button_to "Створити Захист", new_defense_process_path, { method: :get, class: "btn btn-outline-success" } %></li>
                <% end %>
                <li class="nav-item">
                    <%= link_to t(:board), board_index_path, { title: "Перейти на сторінку #{:board}", class: "nav-link active", 'aria-current': "page" } %>
                </li>
                <li class="nav-item">
                    <%= link_to "Поточні захисти", defense_processes_path, { title: "Перейти на сторінку 'Поточні захисти'", class: "nav-link" } %>
                </li>
                <li class="nav-item">
                    <%= link_to "Комісії", commissions_path, { title: "Перейти на сторінку 'Комісії'", class: "nav-link" } %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" title="Перейти на сторінку 'Історія'">Історія</a>
                </li>
                <li class="nav-item">
                    <%= link_to "Вчительський склад", teachers_path, { title: "Перейти на сторінку 'Вчительський склад'", class: "nav-link", 'aria-current': "page" } %>
                </li>
                <li class="nav-item">
                    <%= link_to "Методи оцінки BOCR", eval_methods_path, { title: "Перейти на сторінку 'Методи оцінки BOCR'", class: "nav-link", 'aria-current': "page" } %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Акаунт
                    </a>
                    <ul class="dropdown-menu dropdown-menu-lg-end">
                        <li><a class="dropdown-item disabled" href="#">Action</a></li>
                        <li><a class="dropdown-item disabled" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><%= link_to 'Налаштування аккаунта', edit_user_registration_path, { class: "dropdown-item", title: 'Налаштування аккаунта' } %></li>
                        <li><%= link_to t('devise.shared.links.sign_out'), destroy_user_session_path, { 'data-turbo-method': :delete, class: "dropdown-item", title: t('devise.shared.links.sign_out') } %></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_icon_links_btns.html.erb
<div class="btn-container">
    <% if back %> 
        <%= link_to back do %>
            <i class="bi bi-arrow-left-circle defense"></i>
        <% end %>
    <% end %>
    <% if edit %>
        <% if can? :update, edit[:resource] %> 
            <%= link_to edit[:path] do %>
                <i class="bi bi-pencil defense"></i>
            <% end %>
        <% end %>
    <% end %>

    <% if delete %> 
        <% if can? :destroy, delete[:resource] %> 
            <%= button_to delete[:path], method: :delete, class: "btn-defense_trash" do %>
                <i class="bi bi-trash defense"></i>
            <% end %>
        <% end %>
    <% end %>

     <% if eye %> 
        <%= link_to eye do %>
            <i class="bi bi-eye eye"></i>
        <% end%>
    <% end %>
</div>